name: build

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
          pip install pytest pytest-cov
          pip install -r requirements.txt
      - run: |
          pytest --cov --cov-report=xml
      - uses: codecov/codecov-action@v2

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
          pip install flake8
          pip install -r requirements.txt
      - run: |
          flake8
